/**
 * 견종 한글명 매핑 (key: registry.dog의 breed id).
 * 통용 표기가 여러 개인 경우 한국에서 가장 익숙한 표기를 채택.
 * 4-build.mts에서 매핑이 없는 견종은 영문명이 그대로 표시된다 (경고 출력).
 *
 * ⚠️ 항목 추가 전 CLAUDE.md의 "추측 절대 금지 원칙" 필독.
 * 통용 표기가 있으면 그것을 우선, 없으면 외래어 표기법에 따른 음차 표기
 * (2026-07-08 변경: UI 전면 한글화 — 이름 표기는 사실 주장이 아닌 표기 변환).
 */
export const nameKo: Record<string, string> = {
  chihuahua: "치와와",
  "siberian-husky": "시베리안 허스키",
  "yorkshire-terrier": "요크셔 테리어",
  "french-bulldog": "프렌치 불도그",
  "german-shepherd": "저먼 셰퍼드",
  "labrador-retriever": "래브라도 리트리버",
  dachshund: "닥스훈트",
  "golden-retriever": "골든 리트리버",
  beagle: "비글",
  bulldog: "불도그",
  "miniature-poodle": "미니어처 푸들",
  "australian-shepherd": "오스트레일리안 셰퍼드",
  "great-dane": "그레이트 데인",
  "german-shorthaired-pointer": "저먼 쇼트헤어드 포인터",
  "shetland-sheepdog": "셔틀랜드 쉽독",
  "standard-poodle": "스탠더드 푸들",
  "shih-tzu": "시츄",
  rottweiler: "로트와일러",
  "staffordshire-bull-terrier": "스태퍼드셔 불 테리어",
  "belgian-malinois": "벨지안 말리노이즈",
  samoyed: "사모예드",
  "pembroke-welsh-corgi": "펨브록 웰시 코기",
  newfoundland: "뉴펀들랜드",
  "doberman-pinscher": "도베르만 핀셔",
  "bichon-frise": "비숑 프리제",
  maltese: "말티즈",
  "miniature-schnauzer": "미니어처 슈나우저",
  "west-highland-white-terrier": "웨스트 하이랜드 화이트 테리어",
  "cocker-spaniel": "코커 스패니얼",
  pug: "퍼그",
  "boston-terrier": "보스턴 테리어",
  "bernese-mountain-dog": "버니즈 마운틴 독",
  pomeranian: "포메라니안",
  weimaraner: "바이마라너",
  "english-springer-spaniel": "잉글리시 스프링어 스패니얼",
  dalmatian: "달마시안",
  "cavalier-king-charles-spaniel": "카발리에 킹 찰스 스패니얼",
  "border-collie": "보더 콜리",
  boxer: "복서",
  "standard-schnauzer": "스탠더드 슈나우저",
  akita: "아키타",
  "russell-terrier": "잭 러셀 테리어",
  "dogue-de-bordeaux": "도그 드 보르도",
  "miniature-pinscher": "미니어처 핀셔",
  "nova-scotia-duck-tolling-retriever": "노바 스코샤 덕 톨링 리트리버",
  bullmastiff: "불마스티프",
  "giant-schnauzer": "자이언트 슈나우저",
  "airedale-terrier": "에어데일 테리어",
  "english-cocker-spaniel": "잉글리시 코커 스패니얼",
  mastiff: "마스티프",
  "english-setter": "잉글리시 세터",
  "shiba-inu": "시바견",
  "toy-poodle": "토이 푸들",
  "american-eskimo": "아메리칸 에스키모",
  brittany: "브리타니",
  "cardigan-welsh-corgi": "카디건 웰시 코기",
  "belgian-tervuren": "벨지안 터뷰렌",
  bloodhound: "블러드하운드",
  "anatolian-shepherd": "아나톨리안 셰퍼드",
  "german-wirehaired-pointer": "저먼 와이어헤어드 포인터",
  "belgian-sheepdog": "벨지안 쉽독",
  "gordon-setter": "고든 세터",
  "italian-greyhound": "이탈리안 그레이하운드",
  "border-terrier": "보더 테리어",
  "flat-coated-retriever": "플랫 코티드 리트리버",
  "chinese-crested": "차이니즈 크레스티드",
  "portuguese-water-dog": "포르투갈 워터 독",
  greyhound: "그레이하운드",
  "old-english-sheepdog": "올드 잉글리시 쉽독",
  "st-bernard": "세인트 버나드",
  papillon: "파피용",
  whippet: "휘핏",
  "american-bulldog": "아메리칸 불도그",
  "rhodesian-ridgeback": "로디지안 리지백",
  "american-staffordshire-terrier": "아메리칸 스태퍼드셔 테리어",
  "scottish-terrier": "스코티시 테리어",
  vizsla: "비즐라",
  pekingese: "페키니즈",
  "great-pyrenees": "그레이트 피레니즈",
  "alaskan-malamute": "알래스칸 맬러뮤트",
  havanese: "하바니즈",
  "chinese-shar-pei": "샤페이",
  "afghan-hound": "아프간 하운드",
  "basset-hound": "바셋 하운드",
  "australian-cattle-dog": "오스트레일리안 캐틀 독",
  "soft-coated-wheaten-terrier": "소프트 코티드 휘튼 테리어",
  "lhasa-apso": "라사 압소",
  "chesapeake-bay-retriever": "체서피크 베이 리트리버",
  pointer: "포인터",
  collie: "콜리",
  "bull-terrier": "불 테리어",
  "irish-wolfhound": "아이리시 울프하운드",
  "irish-setter": "아이리시 세터",
  "cane-corso": "카네 코르소",
  "chow-chow": "차우차우",
  "cairn-terrier": "케언 테리어",
  basenji: "바센지",
  "irish-water-spaniel": "아이리시 워터 스패니얼",
  "polish-lowland-sheepdog": "폴리시 로랜드 쉽독",
  "norwich-terrier": "노리치 테리어",
  "german-pinscher": "저먼 핀셔",
  "ibizan-hound": "이비잔 하운드",
  saluki: "살루키",
  boerboel: "보어보엘",
  "bearded-collie": "비어디드 콜리",
  puli: "풀리",
  "lakeland-terrier": "레이클랜드 테리어",
  "mexican-hairless-dog": "숄로이츠퀸틀리",
  "welsh-springer-spaniel": "웰시 스프링어 스패니얼",
  borzoi: "보르조이",
  "greater-swiss-mountain-dog": "그레이터 스위스 마운틴 독",
  briard: "브리아드",
  "dutch-shepherd": "더치 셰퍼드",
  "wirehaired-pointing-griffon": "와이어헤어드 포인팅 그리펀",
  "petit-basset-griffon-vendéen": "프티 바세 그리퐁 방데앙",
  "lagotto-romagnolo": "라고토 로마뇰로",
  "treeing-walker-coonhound": "트리잉 워커 쿤하운드",
  "tibetan-terrier": "티베탄 테리어",
  "irish-terrier": "아이리시 테리어",
  "standard-manchester-terrier": "맨체스터 테리어",
  "finnish-spitz": "핀니시 스피츠",
  "american-foxhound": "아메리칸 폭스하운드",
  "neapolitan-mastiff": "나폴리탄 마스티프",
  "bedlington-terrier": "베들링턴 테리어",
  "spinone-italiano": "스피노네 이탈리아노",
  "finnish-lapphund": "핀니시 라프훈트",
  "norwegian-elkhound": "노르웨이안 엘크하운드",
  "toy-manchester-terrier": "토이 맨체스터 테리어",
  "silky-terrier": "실키 테리어",
  keeshond: "키스혼드",
  "welsh-terrier": "웰시 테리어",
  leonberger: "레온베르거",
  affenpinscher: "아펜핀셔",
  "coton-de-tulear": "코통 드 툴레아",
  "irish-red-and-white-setter": "아이리시 레드 앤 화이트 세터",
  "black-and-tan-coonhound": "블랙 앤 탄 쿤하운드",
  "catahoula-leopard-dog": "카타훌라 레오파드 독",
  "bouvier-des-flandres": "부비에 데 플랑드르",
  kuvasz: "쿠바스",
  "australian-terrier": "오스트레일리안 테리어",
  "japanese-chin": "재패니즈 친",
  "redbone-coonhound": "레드본 쿤하운드",
  "australian-kelpie": "오스트레일리안 켈피",
  "dogo-argentino": "도고 아르헨티노",
  "scottish-deerhound": "스코티시 디어하운드",
  "tibetan-spaniel": "티베탄 스패니얼",
  "toy-fox-terrier": "토이 폭스 테리어",
  "brussels-griffon": "브뤼셀 그리펀",
  "rat-terrier": "랫 테리어",
  schipperke: "스키퍼키",
  "curly-coated-retriever": "컬리 코티드 리트리버",
  "kerry-blue-terrier": "케리 블루 테리어",
  "norfolk-terrier": "노퍽 테리어",
  "english-toy-spaniel": "잉글리시 토이 스패니얼",
  "dandie-dinmont-terrier": "댄디 딘몬트 테리어",
  "clumber-spaniel": "클럼버 스패니얼",
  komondor: "코몬도르",
  "american-leopard-hound": "아메리칸 레오파드 하운드",
  "lancashire-heeler": "랭커셔 힐러",
  "plott-hound": "플롯 하운드",
  "german-spitz": "저먼 스피츠",
  "alaskan-klee-kai": "알래스칸 클리 카이",
  "bluetick-coonhound": "블루틱 쿤하운드",
  "portuguese-podengo-pequeno": "포르투기즈 포뎅고 페케노",
  "skye-terrier": "스카이 테리어",
  azawakh: "아자와크",
  // 믹스견 — 통용 표기 (확립된 것)
  puggle: "퍼글",
  labradoodle: "래브라두들",
  goldendoodle: "골든두들",
  cockapoo: "코카푸",
  maltipoo: "말티푸",
  pomsky: "폼스키",
  cavapoo: "카바푸",
  bernedoodle: "버니두들",
  // 믹스견 — 통용 표기 미확립, 외래어 표기법 음차 (2026-07-08 한글화 방침)
  chiweenie: "치위니",
  yorkipoo: "요키푸",
  schnoodle: "슈누들",
  morkie: "몰키",
  aussiedoodle: "오시두들",
  chorkie: "초키",
  pitsky: "핏스키",
  goldador: "골다도르",
  shorkie: "쇼키",
  boxador: "복사도르",
  bullmatian: "불마시안",
  doxiepoo: "독시푸",
  sheepadoodle: "쉽아두들",
  cheagle: "치글",
  springador: "스프링가도르",
  shihpoo: "시푸",
  bordoodle: "보더두들",
  cockalier: "코카리어",
  cavachon: "카바숑",
};
